# Generated by Django 5.0.4 on 2024-06-15 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('BrandID', models.AutoField(primary_key=True, serialize=False)),
                ('BrandName', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=80)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Gender', models.CharField(max_length=20)),
                ('AnnualIncome', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('DealerID', models.AutoField(primary_key=True, serialize=False)),
                ('DealerName', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('FactoryID', models.AutoField(primary_key=True, serialize=False)),
                ('FactoryName', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierID', models.AutoField(primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('ModelID', models.AutoField(primary_key=True, serialize=False)),
                ('ModelName', models.CharField(max_length=80)),
                ('BrandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='appStart.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('VIN', models.AutoField(primary_key=True, serialize=False)),
                ('ModelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='appStart.model')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('OptionID', models.AutoField(primary_key=True, serialize=False)),
                ('Color', models.CharField(max_length=80)),
                ('Engine', models.CharField(max_length=80)),
                ('Transmission', models.CharField(max_length=80)),
                ('CarVIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='appStart.car')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('SaleID', models.AutoField(primary_key=True, serialize=False)),
                ('SaleDate', models.DateTimeField(auto_now_add=True)),
                ('CarVIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appStart.car')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appStart.customer')),
                ('DaelerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appStart.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='DealerBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_brands', to='appStart.brand')),
                ('DealerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_brands', to='appStart.dealer')),
            ],
            options={
                'unique_together': {('BrandID', 'DealerID')},
            },
        ),
        migrations.CreateModel(
            name='FactoryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_brands', to='appStart.brand')),
                ('FactoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_brands', to='appStart.factory')),
            ],
            options={
                'unique_together': {('BrandID', 'FactoryID')},
            },
        ),
    ]
