# Generated by Django 5.0.6 on 2024-06-18 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStart', '0002_rename_daelerid_sale_dealerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='DealerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='appStart.dealer'),
        ),
        migrations.AddField(
            model_name='option',
            name='OptionPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
