# Generated by Django 5.0.6 on 2024-06-18 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStart', '0003_option_dealerid_option_optionprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='DealerID',
        ),
        migrations.AddField(
            model_name='option',
            name='SupplierID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='appStart.supplier'),
        ),
    ]
