# Generated by Django 5.0.6 on 2024-06-18 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStart', '0005_alter_option_supplierid'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='ProduceTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
