# Generated by Django 5.0.6 on 2024-06-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStart', '0006_option_producetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Status',
            field=models.BooleanField(choices=[('True', 'Sold'), ('False', 'ForSale')], default=False),
        ),
    ]
