# Generated by Django 5.0.6 on 2024-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStart', '0007_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Status',
            field=models.CharField(choices=[('1', 'ForSale'), ('0', 'Sold')], default=False, max_length=1),
        ),
    ]
