# Generated by Django 5.0.6 on 2024-06-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStart', '0009_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='CarVIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='appStart.car'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='appStart.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='DealerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='appStart.dealer'),
        ),
    ]
