# Generated by Django 5.0.4 on 2024-05-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('BrandID', models.IntegerField(primary_key=True, serialize=False)),
                ('BrandName', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=80)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=80)),
                ('Gender', models.CharField(max_length=20)),
                ('AnnualIncome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('DealerID', models.IntegerField(primary_key=True, serialize=False)),
                ('DealerName', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Factories',
            fields=[
                ('FactoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('FactoryName', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('SupplierID', models.IntegerField(primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='DealerBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.brands')),
                ('DealerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dealers')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DealerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dealers')),
                ('FactoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.factories')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('ModelID', models.IntegerField(primary_key=True, serialize=False)),
                ('ModelName', models.CharField(max_length=80)),
                ('BrandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.brands')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('VIN', models.IntegerField(primary_key=True, serialize=False)),
                ('ModelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.models')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('OptionID', models.IntegerField(primary_key=True, serialize=False)),
                ('Color', models.CharField(max_length=80)),
                ('Engine', models.CharField(max_length=80)),
                ('Transmission', models.CharField(max_length=80)),
                ('CarVIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cars')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('SaleID', models.IntegerField(primary_key=True, serialize=False)),
                ('SaleDate', models.DateTimeField(auto_now_add=True)),
                ('CarVIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cars')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customers')),
                ('DaelerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dealers')),
            ],
        ),
    ]
